apiVersion: "v1"
kind: "BuildConfig"
metadata: 
  name: "tetris-build"
spec:
  runPolicy: "Serial"
  source:
    git: 
      uri: "https://github.com/haomingyin/tetris"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: tetris-is:latest
      
